[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.json', 'php82Extensions.bcmath', 'php82Extensions.fileinfo', 'nodejs_20']

[phases.build]
cmds = [
    'composer install --optimize-autoloader --no-dev',
    'php artisan optimize',
    'npm install',
    'npm run build'
]

[start]
cmd = 'php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link && php -S 0.0.0.0:$PORT -t public'
