[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.json', 'php82Extensions.bcmath', 'php82Extensions.fileinfo']

[phases.build]
cmds = [
    'composer install --optimize-autoloader --no-dev'
]

[start]
cmd = 'php artisan config:cache && php artisan route:cache && php artisan storage:link && php -S 0.0.0.0:$PORT -t public'
