[phases.setup]
nixPkgs = [
    'php82',
    'composer',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.mbstring',
    'php82Extensions.tokenizer',
    'php82Extensions.xml',
    'php82Extensions.ctype',
    'php82Extensions.json',
    'php82Extensions.bcmath',
    'php82Extensions.fileinfo',
    'php82Extensions.curl',
    'php82Extensions.openssl',
    'php82Extensions.dom',
    'php82Extensions.gd',
    'php82Extensions.iconv',
    'php82Extensions.intl',
    'php82Extensions.phar',
    'php82Extensions.session',
    'php82Extensions.simplexml',
    'php82Extensions.zip'
]

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-interaction']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'
